### ISSUE TITLE
Runtime program fails when running Qiskit locally while working on IQX

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit-Partners/qiskit-runtime#56]
I encountered an error while running [the circuit runner tutorial](https://qiskit.org/documentation/partners/qiskit_runtime/tutorials/01_circuit_runner.html) in Qiskit Nature locally while it runs perfectly on IQX.

I have `ibm-q-internal` provider and I used `ibmq_qasm_simulator` as backend. 

Qiskit version: 0.28.0
qiskit-terra: 0.18.0
qiskit-ibmq-provider version: 0.15.0
OS: macOS 11.4 Big Sur

Error message:
```
---------------------------------------------------------------------------
RuntimeJobFailureError                    Traceback (most recent call last)
<ipython-input-20-f745315ba2cc> in <module>
----> 1 res = job.result()

~/opt/anaconda3/envs/iqc21f/lib/python3.8/site-packages/qiskit/providers/ibmq/runtime/runtime_job.py in result(self, timeout, wait, decoder)
    146             self.wait_for_final_state(timeout=timeout, wait=wait)
    147             if self._status == JobStatus.ERROR:
--> 148                 raise RuntimeJobFailureError(f"Unable to retrieve job result. "
    149                                              f"{self.error_message()}")
    150             result_raw = self._api_client.job_results(job_id=self.job_id())

RuntimeJobFailureError: 'Unable to retrieve job result. Job c3o0ebi8t4lsk6v07jng has failed:\n2021-07-15T10:00:17.825118835Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.08321 (ms)\n2021-07-15T10:00:17.825774913Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.05102 (ms)\n2021-07-15T10:00:17.826260105Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.05627 (ms)\n2021-07-15T10:00:17.826730641Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.07224 (ms)\n2021-07-15T10:00:17.827172969Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.08965 (ms)\n2021-07-15T10:00:17.827691162Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.00000 (ms)\n2021-07-15T10:00:17.828120568Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06223 (ms)\n2021-07-15T10:00:17.828593301Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06199 (ms)\n2021-07-15T10:00:17.830088234Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06366 (ms)\n2021-07-15T10:00:17.830590798Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06270 (ms)\n2021-07-15T10:00:17.831103059Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06247 (ms)\n2021-07-15T10:00:17.832110159Z 07/15/2021 10:00:17 AM - asyncio - DEBUG Using selector: EpollSelector\n2021-07-15T10:00:17.832363445Z nats_client.connect:DEBUG:2021-07-15 10:00:17,832: Connecting to server at tls://nats-cluster.nats-io.svc.cluster.local:4222\n2021-07-15T10:00:17.853085559Z Traceback (most recent call last):\n2021-07-15T10:00:17.853110181Z   File "/code/program_starter.py", line 45, in <module>\n2021-07-15T10:00:17.853115615Z     final_result = main(backend, messenger, **user_params)\n2021-07-15T10:00:17.853122466Z   File "/code/program.py", line 24, in main\n2021-07-15T10:00:17.853127563Z     circuits = transpile(circuits,\n2021-07-15T10:00:17.853133653Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 235, in transpile\n2021-07-15T10:00:17.853141844Z     transpile_args = _parse_transpile_args(circuits, backend, basis_gates, coupling_map,\n2021-07-15T10:00:17.853148552Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 431, in _parse_transpile_args\n2021-07-15T10:00:17.853154625Z     output_name = _parse_output_name(output_name, circuits)\n2021-07-15T10:00:17.853160973Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 739, in _parse_output_name\n2021-07-15T10:00:17.853166884Z     return [circuit.name for circuit in circuits]\n2021-07-15T10:00:17.853173430Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 739, in <listcomp>\n2021-07-15T10:00:17.853177755Z     return [circuit.name for circuit in circuits]\n2021-07-15T10:00:17.853182736Z AttributeError: \'dict\' object has no attribute \'name\'\n'
```

**Comment by HuangJunye** [comment]
Error message shown on the job result page on IQX

```
2021-07-15T10:00:17.825118835Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.08321 (ms)
2021-07-15T10:00:17.825774913Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.05102 (ms)
2021-07-15T10:00:17.826260105Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.05627 (ms)
2021-07-15T10:00:17.826730641Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.07224 (ms)
2021-07-15T10:00:17.827172969Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.08965 (ms)
2021-07-15T10:00:17.827691162Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.00000 (ms)
2021-07-15T10:00:17.828120568Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06223 (ms)
2021-07-15T10:00:17.828593301Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06199 (ms)
2021-07-15T10:00:17.830088234Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06366 (ms)
2021-07-15T10:00:17.830590798Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06270 (ms)
2021-07-15T10:00:17.831103059Z 07/15/2021 10:00:17 AM - qiskit.compiler.assembler - INFO Total Assembly Time - 0.06247 (ms)
2021-07-15T10:00:17.832110159Z 07/15/2021 10:00:17 AM - asyncio - DEBUG Using selector: EpollSelector
2021-07-15T10:00:17.832363445Z nats_client.connect:DEBUG:2021-07-15 10:00:17,832: Connecting to server at tls://nats-cluster.nats-io.svc.cluster.local:4222
2021-07-15T10:00:17.853085559Z Traceback (most recent call last):
2021-07-15T10:00:17.853110181Z   File "/code/program_starter.py", line 45, in <module>
2021-07-15T10:00:17.853115615Z     final_result = main(backend, messenger, **user_params)
2021-07-15T10:00:17.853122466Z   File "/code/program.py", line 24, in main
2021-07-15T10:00:17.853127563Z     circuits = transpile(circuits,
2021-07-15T10:00:17.853133653Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 235, in transpile
2021-07-15T10:00:17.853141844Z     transpile_args = _parse_transpile_args(circuits, backend, basis_gates, coupling_map,
2021-07-15T10:00:17.853148552Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 431, in _parse_transpile_args
2021-07-15T10:00:17.853154625Z     output_name = _parse_output_name(output_name, circuits)
2021-07-15T10:00:17.853160973Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 739, in _parse_output_name
2021-07-15T10:00:17.853166884Z     return [circuit.name for circuit in circuits]
2021-07-15T10:00:17.853173430Z   File "/usr/local/lib/python3.8/site-packages/qiskit/compiler/transpiler.py", line 739, in <listcomp>
2021-07-15T10:00:17.853177755Z     return [circuit.name for circuit in circuits]
2021-07-15T10:00:17.853182736Z AttributeError: 'dict' object has no attribute 'name'

```

**Comment by HuangJunye** [comment]
Works on Qiskit 0.27.0 without problems. Thank you :)
